NewISE/Areas/Parametri/Controllers/ParamValutaUfficioController.cs
using NewISE.Areas.Parametri.Models;
using NewISE.Areas.Parametri.Models.dtObj;
using NewISE.Models.DBModel.dtObj;
using NewISE.Models;
using NewISE.Models.DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace NewISE.Areas.Parametri.Controllers
{
    public class ParamValutaUfficioController : Controller
    {
        // GET: Parametri/ParamPercMaggAbitaz/PercentualeMaggAbitazione
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [Authorize(Roles = "1 ,2")]
        public ActionResult ValutaUfficio(bool escludiAnnullati, decimal idLivello = 0, decimal idUfficio = 0)
        {
            var r = new List<SelectListItem>();
            List<ValuteModel> llm = new List<ValuteModel>();
            List<UfficiModel> llm1 = new List<UfficiModel>();
            ViewBag.escludiAnnullati = escludiAnnullati;
            List<ValutaUfficioModel> libm = new List<ValutaUfficioModel>();
            try
            {
                decimal tmp = AggiornaListaPerCombo(idLivello, idUfficio);
                using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                {
                    ViewBag.idMinimoNonAnnullato = dtib.Get_Id_ValutaUfficioNonAnnullato(tmp);
                    libm = dtib.getListValutaUfficio(tmp, escludiAnnullati).OrderBy(a => a.dataInizioValidita).ThenBy(a => a.dataFineValidita).ToList();
                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
            return PartialView(libm);
        }

        [HttpPost]
        [Authorize(Roles = "1 ,2")]
        public ActionResult ValutaUfficioLivello(bool escludiAnnullati, decimal idValuta = 0, decimal idUfficio = 0)
        {
            List<ValutaUfficioModel> libm = new List<ValutaUfficioModel>();
            var r = new List<SelectListItem>();
            List<ValuteModel> llm = new List<ValuteModel>();
            List<UfficiModel> llm1 = new List<UfficiModel>();
            ViewBag.escludiAnnullati = escludiAnnullati;
            try
            {
                decimal tmp = AggiornaListaPerCombo(idValuta, idUfficio);
                using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                {
                    ViewBag.idMinimoNonAnnullato = dtib.Get_Id_ValutaUfficioNonAnnullato(tmp);
                    libm = dtib.getListValutaUfficio(tmp, escludiAnnullati).OrderBy(a => a.dataInizioValidita).ThenBy(a => a.dataFineValidita).ToList();
                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
            return PartialView("ValutaUfficio", libm);
        }

        [HttpPost]
        [Authorize(Roles = "1, 2")]
        public ActionResult NuovaValutaUfficio(decimal idValuta, decimal idUfficio, bool escludiAnnullati)
        {
            var r = new List<SelectListItem>();
            try
            {
                AggiornaListaPerCombo(idValuta, idUfficio);
                ViewBag.escludiAnnullati = escludiAnnullati;
                return PartialView();
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
        }

        [HttpPost]
        [Authorize(Roles = "1, 2")]
        [ValidateAntiForgeryToken]
        public ActionResult InserisciValutaUfficio(ValutaUfficioModel ibm, bool escludiAnnullati = true, bool aggiornaTutto = false)
        {
            var r = new List<SelectListItem>();
            ViewBag.escludiAnnullati = escludiAnnullati;
            List<ValutaUfficioModel> libm = new List<ValutaUfficioModel>();
            try
            {
                if (ModelState.IsValid)
                {
                    using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                    {
                        dtib.SetValutaUfficio(ibm, aggiornaTutto);
                    }
                    decimal tmp = AggiornaListaPerCombo(ibm.idValuta, ibm.idUfficio);
                    using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                    {
                        ViewBag.idMinimoNonAnnullato = dtib.Get_Id_ValutaUfficioNonAnnullato(tmp);
                        libm = dtib.getListValutaUfficio(tmp, escludiAnnullati).OrderBy(a => a.dataInizioValidita).ThenBy(a => a.dataFineValidita).ToList();
                    }
                    return PartialView("ValutaUfficio", libm);
                    //  return RedirectToAction("PercentualeMaggAbitazione", new { escludiAnnullati = escludiAnnullati, idLivello = ibm.idLivello });
                }
                else
                {
                    //using (dtParValute dtl = new dtParValute())
                    //{
                    //    var lm =dtl.GetValute(ibm.idValuta);
                    //    ViewBag.Livello = lm;
                    //}
                    decimal tmp = AggiornaListaPerCombo(ibm.idValuta, ibm.idUfficio);
                    using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                    {
                        libm = dtib.getListValutaUfficio(ibm.idUfficio, escludiAnnullati).OrderBy(a => a.dataInizioValidita).ThenBy(a => a.dataFineValidita).ToList();
                    }
                    return PartialView("NuovaValutaUfficio", ibm);
                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
        }

        [HttpPost]
        [Authorize(Roles = "1, 2")]
        public ActionResult EliminaValutaUfficio(bool escludiAnnullati, decimal idValuta, decimal idValutaUfficio, decimal idUfficio)
        {
            ViewBag.escludiAnnullati = escludiAnnullati;
            List<ValutaUfficioModel> libm = new List<ValutaUfficioModel>();
            try
            {
                using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                {
                    dtib.DelValutaUfficio(idValutaUfficio);
                }
                decimal tmp = AggiornaListaPerCombo(idValuta, idUfficio);
                using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                {
                    ViewBag.idMinimoNonAnnullato = dtib.Get_Id_ValutaUfficioNonAnnullato(tmp);
                    libm = dtib.getListValutaUfficio(tmp, escludiAnnullati).OrderBy(a => a.dataInizioValidita).ThenBy(a => a.dataFineValidita).ToList();
                }
                return PartialView("ValutaUfficio", libm);
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
        }
        //decimal[] AggiornaListaPerCombo(decimal idValuta, decimal idUfficio )
        decimal AggiornaListaPerCombo(decimal idValuta, decimal idUfficio)
        {
            var r = new List<SelectListItem>();
            List<ValuteModel> llm = new List<ValuteModel>();
            idValuta = 0;
            using (NewISE.Areas.Parametri.Models.dtObj.dtValute dtl = new NewISE.Areas.Parametri.Models.dtObj.dtValute())
            {
                llm = dtl.getListValute().OrderBy(a => a.descrizioneValuta).ToList();
                if (llm != null && llm.Count > 0)
                {
                    r = (from t in llm
                         select new SelectListItem
                         {
                             Text = t.descrizioneValuta,
                             Value = t.idValuta.ToString()
                         }).ToList();

                    if (idValuta == 0)
                    {
                        r.First().Selected = true;
                        idValuta = Convert.ToDecimal(r.First().Value);
                    }
                    else
                    {
                        var temp = r.Where(a => a.Value == idValuta.ToString()).ToList();
                        if (temp.Count == 0)
                        {
                            r.First().Selected = true;
                            idValuta = Convert.ToDecimal(r.First().Value);
                        }
                        else
                            r.Where(a => a.Value == idValuta.ToString()).First().Selected = true;
                    }
                }
                ViewBag.ValutaList = r;
            }

            List<UfficiModel> llm1 = new List<UfficiModel>();
            r = new List<SelectListItem>();
            using (dtUffici dtl1 = new dtUffici())
            {
                llm1 = dtl1.GetUffici().OrderBy(a => a.descUfficio).ToList();
                if (llm1 != null && llm1.Count > 0)
                {
                    r = (from t in llm1
                         select new SelectListItem()
                         {
                             Text = t.descUfficio,
                             Value = t.idUfficio.ToString()
                         }).ToList();

                    if (idUfficio == 0)
                    {
                        r.First().Selected = true;
                        idUfficio = Convert.ToDecimal(r.First().Value);
                    }
                    else
                    {
                        var temp = r.Where(a => a.Value == idUfficio.ToString()).ToList();
                        if (temp.Count == 0)
                        {
                            r.First().Selected = true;
                            idUfficio = Convert.ToDecimal(r.First().Value);
                        }
                        else
                            r.Where(a => a.Value == idUfficio.ToString()).First().Selected = true;
                    }
                }
                ViewBag.UfficiList = r;
            }
            //return new decimal[] { idValuta, idUfficio };
            return idUfficio;

NewISE/Areas/Parametri/Views/ParamValutaUfficio/NuovaValutaUfficio.cshtml
@model NewISE.Models.DBModel.ValutaUfficioModel
@using NewISE.Models.DBModel;

<script src="~/Scripts/autoNumeric/autoNumeric.min.js"></script>
<script src="~/Scripts/globalize.0.1.3/globalize.js"></script>
<script src="~/Scripts/globalize.0.1.3/cultures/globalize.culture.it-IT.js"></script>

@Scripts.Render("~/bundles/jqueryval")

@{

    //ValuteModel lm = (ValuteModel)ViewBag.Valuta;
    //string descrizioneValue = lm.descrizioneValuta;
    bool escludiAnnullati = (bool)ViewBag.escludiAnnullati;
    //decimal idValuta = lm.idValuta;
    //UfficiModel lm1 = (UfficiModel)ViewBag.Ufficio;
    //string descrizioneUfficio = lm1.descUfficio;
    //decimal idUfficio= lm1.idUfficio;

    IEnumerable<SelectListItem> GruppoValute = (IEnumerable<SelectListItem>)ViewBag.ValutaList;
    string idValuta = GruppoValute.Where(x => x.Selected).FirstOrDefault().Value;
    string descrizioneValue = GruppoValute.Where(x => x.Selected).FirstOrDefault().Text;

    IEnumerable<SelectListItem> GruppoUffici = (IEnumerable<SelectListItem>)ViewBag.UfficiList;
    string idUfficio = GruppoUffici.Where(x => x.Selected).FirstOrDefault().Value;
    string descrizioneUfficio = GruppoUffici.Where(x => x.Selected).FirstOrDefault().Text;
}

@using (Ajax.BeginForm("InserisciValutaUfficio", "ParamValutaUfficio", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divPViewParametri", OnFailure = "ErroreElaborazioneAjax" }, new { id = "formValutaUfficio" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        <div class="row">
            <div class="col-xs-offset-2 col-xs-10">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
        @*@Html.HiddenFor(model => model.idValuta)*@
        @Html.HiddenFor(model => model.idUfficio)

        <input type="hidden" id="escludiAnnullati" , name="escludiAnnullati" value="@escludiAnnullati.ToString()" />
        <input type="hidden" id="aggiornaTutto" , name="aggiornaTutto" />
        <div class="form-group">
            <div class="row">
                <div class="col-xs-2 text-right">
                    <label>Ufficio </label>
                </div>
                <div class="col-xs-5">
                    <div class="panel panel-default">
                        <label style="padding-left:5px; padding-top:5px; font:bold;">@descrizioneUfficio.ToString()</label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-2 text-right">
                    <label>Seleziona Valuta</label>
                </div>
                <div class="col-xs-5">
                    @Html.DropDownList("idValuta", ViewBag.ValutaList as IEnumerable<SelectListItem>,
                     new { @class = "form-control select2 select2-select" })
                </div>
            </div><br />
            <div class="row">
                @Html.Label("Data Variazione", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.dataInizioValidita, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.dataInizioValidita, "", new { @class = "text-danger" })
                </div>
                <div id="divChkAgg" class="col-xs-5">
                    <div style="display:inline-block;">
                        <input type="checkbox" id="aggiornaTuttoX" name="aggiornaTuttoX" onclick="AggiornaTutto()" />
                    </div>
                    <div style="vertical-align:middle; display:inline-block;">
                        <label>Aggiorna tutto</label>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Inserisci" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-xs-offset-2 col-xs-10">
        <a href="#" onclick="TornaElencoIb();">Torna all'elenco delle Valute Ufficio</a>
    </div>
</div>

<script type="text/javascript">
    Globalize.culture("it-IT");



    $.validator.methods.number = function (value, element) {
        //debugger;
        return this.optional(element) || !isNaN(Globalize.parseFloat(value));
    };

    $.validator.methods.date = function (value, element) {
        return this.optional(element) || Globalize.parseDate(value, "dd/MM/yyyy", "it-IT");
    }

    $('#dataInizioValidita').datepicker({
        inline: true,
        changeMonth: true,
        changeYear: true,
    });
    $('#dataFineValidita').datepicker({
        inline: true,
        changeMonth: true,
        changeYear: true,
    });

    function AggiornaTutto() {

        var chk = false;
        if ($("#aggiornaTuttoX").is(":checked")) {
            chk = true;
        }
        $("#aggiornaTutto").val(chk);
    }
    $("#idValuta").select2({
        placeholder: "Seleziona Descrizione Valuta",
        allowClear: true,
        language: "it",
        width: '150'

    });

    function TornaElencoIb() {
        rotta = "/Parametri/ParamValutaUfficio/ValutaUfficioLivello";

        var idValuta = parseFloat('@idValuta');
        var idUfficio = parseFloat('@idUfficio');


        if (isNaN(idValuta)) {
            $("#divPViewParametri").empty();
            return false;
        }

        if (isNaN(idUfficio)) {
            $("#divPViewParametri").empty();
            return false;
        }

        var chk = false;
        if ($("#escludiAnnullati").is(":checked")) {
            chk = true;
        }

        $.ajax({
            type: "POST",
            url: rotta,
            data: { idValuta: idValuta, idUfficio: idUfficio, escludiAnnullati: chk },
            dataType: 'html',
            beforeSend: function () {
                //debugger;
                //VerificaAutenticazione();
                //$("#DialogNewDoc").dialog("destroy");
                //$("#divEffettoLoadAutNoDoc").show("slow");
            },
            success: function (result) {
                //debugger;
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                $("#divPViewParametri").empty();
                $("#divPViewParametri").html(result);

                //RicercaDocumenti();

            },
            complete: function () {
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                //                $("#Centro").getNiceScroll().resize();
            },
            error: function (jqXHR, textStatus, errorThrow) {
                //debugger;
                var msg = errorThrow.err;
                AlertDialog(msg);
            }

        });
    }
</script>

NewISE/Areas/Parametri/Views/ParamValutaUfficio/ValutaUfficio.cshtml
@model IEnumerable<NewISE.Models.DBModel.ValutaUfficioModel>
@using NewISE.Areas.Parametri.Models.dtObj;
@using NewISE.Models.Tools;
@{
    bool escludiAnnullati = (bool)ViewBag.escludiAnnullati;
    decimal idMinimoNonAnnullato = (decimal)ViewBag.idMinimoNonAnnullato;


    //IEnumerable<SelectListItem> GruppoValute = (IEnumerable<SelectListItem>)ViewBag.ValutaList;
    //string idValuta = GruppoValute.Where(x => x.Selected).FirstOrDefault().Value;
    //string descrizioneValue = GruppoValute.Where(x => x.Selected).FirstOrDefault().Text;

    IEnumerable<SelectListItem> GruppoUffici = (IEnumerable<SelectListItem>)ViewBag.UfficiList;
    string idUfficio = GruppoUffici.Where(x => x.Selected).FirstOrDefault().Value;
    string descrizioneUfficio = GruppoUffici.Where(x => x.Selected).FirstOrDefault().Text;
}

<p>
    <a id="btnInsNuovaValutazioneUfficio" href="#" onclick="NuovaValutaUfficio()">Inserisci Nuova Valuta Ufficio</a>
</p>
<p>
    <div class="form-group">
        @Html.Label("lblUfficio0", "Seleziona Ufficio", new { @class = "control-label" })
        <div id="divCombo">
            <div class="select2-container select2-container--classic">
                @Html.DropDownList("idUfficio", ViewBag.UfficiList as IEnumerable<SelectListItem>, new { @class = "form-control select2 select2-select", @onchange = "PrelevaPValutaUfficio();", @onClick = "PrelevaPValutaUfficio();" })
            </div>
        </div>
    </div>
</p>
@*<p>
        <div class="form-group">
            @Html.Label("lblValuta00", "Seleziona Valuta", new { @class = "control-label" })
            <div id="divCombo">
                <div class="select2-container select2-container--classic">
                    @Html.DropDownList("idValuta", ViewBag.ValutaList as IEnumerable<SelectListItem>, new { @class = "form-control select2 select2-select", @onchange = "PrelevaPValutaUfficio();", @onClick = "PrelevaPValutaUfficio();" })
                </div>
            </div>
        </div>
    </p>*@

<table id="tbParValutaUfficio" class="display" cellspacing="0">
    <thead>
        <tr>
            @*<th class="text-center">
                    @Html.DisplayNameFor(model => model.Livello.DescLivello)
                </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.dataInizioValidita)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.dataFineValidita)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Valuta.descrizioneValuta)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.dataAggiornamento)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.annullato)
            </th>
            <th class="text-center"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Livello.DescLivello)
                    </td>*@
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.dataInizioValidita)
                </td>
                @if (item.dataFineValidita != Utility.DataFineStop())
                {
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.dataFineValidita)
                    </td>
                }
                else
                {
                    <td></td>
                }
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.Valuta.descrizioneValuta)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.dataAggiornamento)
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(modelItem => item.annullato)
                </td>
                <td style="text-align:center;">
                    @using (dtParValutaUfficio dtib = new dtParValutaUfficio())
                    {
                        if (dtib.ParValutaUfficioAnnullato(item))
                        {
                            <a href="#" class="disabled"><img alt="Elimina" src="~/Immagini/EliminazioneDisable.png" width="25" /></a>
                        }
                        else
                        {
                            if (item.idValutaUfficio == idMinimoNonAnnullato)
                            {
                                <a href="#" class="disabled"><img alt="Elimina" src="~/Immagini/EliminazioneDisable.png" width="25" /></a>
                            }
                            else
                            {
                                <a href="#" onclick="EliminaValutaUfficio(@item.idValutaUfficio)"><img alt="Elimina" src="~/Immagini/Eliminazione.png" width="25" /></a>
                            }
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="dialog-confirm" title="Elimina Parametro Valuta Ufficio?" class="hide">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span>Si vuole procedere con l'eliminazione della Valuta Ufficio?</p>
</div>

<script type="text/javascript">
    $('.display').DataTable({
        //"ordering":false,
        "language": {
            "sEmptyTable": "Nessun dato presente nella tabella",
            "sInfo": "Vista da _START_ a _END_ di _TOTAL_ elementi",
            "sInfoEmpty": "Vista da 0 a 0 di 0 elementi",
            "sInfoFiltered": "(filtrati da _MAX_ elementi totali)",
            "sInfoPostFix": "",
            "sInfoThousands": ".",
            "sLengthMenu": "Visualizza _MENU_ elementi",
            "sLoadingRecords": "Caricamento...",
            "sProcessing": "Elaborazione...",
            "sSearch": "Cerca:",
            "sZeroRecords": "La ricerca non ha portato alcun risultato.",
            "oPaginate": {
                "sFirst": "Inizio",
                "sPrevious": "Precedente",
                "sNext": "Successivo",
                "sLast": "Fine"
            },
            "oAria": {
                "sSortAscending": ": attiva per ordinare la colonna in ordine crescente",
                "sSortDescending": ": attiva per ordinare la colonna in ordine decrescente"
            }
        },
        "info": true,
        "lengthChange": false,
        "pageLength": 5,
        "searching": false,
        "paging": false,
        "bJQueryUI": true,
        "sDom": 'lfrtip',
        "scrollY": 400,
        "scrollCollapse": true,
        "columnDefs": [
                { "targets": [0, 1, 3], "type": 'date-euro' },
                //{ "targets": [3], "type": 'numeric-comma' },
                { "targets": [4, 5], "orderable": false },
        ],
        "order": [[0, "desc"]]
    });

    $("#idValuta").select2({
        placeholder: "Seleziona la Valuta",
        allowClear: true,
        language: "it",
        width: '150'

    });

    $("#idUfficio").select2({
        placeholder: "Seleziona Ufficio",
        allowClear: true,
        language: "it",
        width: '150'

    });

    $("#btnInsNuovaValutazioneUfficio").button();


    function PrelevaPValutaUfficio() {
        // debugger;
        rotta = "/Parametri/ParamValutaUfficio/ValutaUfficioLivello";

        var idValuta = parseInt($("#idValuta").select2('val'));
        $("#hiTipoContributo").val(idValuta);

        var idUfficio = parseInt($("#idUfficio").select2('val'));
        $("#hiIdUfficio").val(idUfficio);

        if (isNaN(idValuta)) {
            //$("#divPViewParametri").empty();
            //return false;
            idValuta = 0;
        }

        if (isNaN(idUfficio)) {
            $("#divPViewParametri").empty();
            return false;
        }

        var chk = false;
        if ($("#escludiAnnullati").is(":checked")) {
            chk = true;
        }

        $.ajax({
            type: "POST",
            url: rotta,
            data: {escludiAnnullati: chk, idValuta: idValuta, idUfficio: idUfficio },
            dataType: 'html',
            beforeSend: function () {
                //debugger;
                //VerificaAutenticazione();
                //$("#DialogNewDoc").dialog("destroy");
                //$("#divEffettoLoadAutNoDoc").show("slow");
            },
            success: function (result) {
                //debugger;
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                $("#divPViewParametri").empty();
                $("#divPViewParametri").html(result);

                //RicercaDocumenti();

            },
            complete: function () {
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                //                $("#Centro").getNiceScroll().resize();
            },
            error: function (jqXHR, textStatus, errorThrow) {
                //debugger;
                var msg = errorThrow.err;
                AlertDialog(msg);
            }

        });

    }

    function NuovaValutaUfficio() {
        //debugger;

        var rotta = "/Parametri/ParamValutaUfficio/NuovaValutaUfficio";
        var idValuta = 0;//parseInt($("#idValuta").select2('val'));
        var idUfficio = parseInt($("#idUfficio").select2('val'));

        //if (isNaN(idValuta)) {
        //    //$("#divPViewParametri").empty();
        //    AlertDialog("Selezionare un livello per procedere.");
        //    return false;
        //}

        if (isNaN(idUfficio)) {
            //$("#divPViewParametri").empty();
            AlertDialog("Selezionare un ufficio per procedere.");
            return false;
        }

        var chk = false;
        if ($("#escludiAnnullati").is(":checked")) {
            chk = true;
        }

        $.ajax({
            type: "POST",
            url: rotta,
            data: { idValuta: idValuta, idUfficio: idUfficio, escludiAnnullati: chk },
            dataType: 'html',
            beforeSend: function () {
                //debugger;
                //VerificaAutenticazione();
                //$("#DialogNewDoc").dialog("destroy");
                //$("#divEffettoLoadAutNoDoc").show("slow");
            },
            success: function (result) {
                //debugger;
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                $("#divPViewParametri").empty();
                $("#divPViewParametri").html(result);

                //RicercaDocumenti();

            },
            complete: function () {
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                //                $("#Centro").getNiceScroll().resize();
            },
            error: function (jqXHR, textStatus, errorThrow) {
                //debugger;
                var msg = errorThrow.err;
                AlertDialog(msg);
            }

        });

    }

    function EliminaValutaUfficio(id) {
        //debugger;
        var rotta = "/Parametri/ParamValutaUfficio/EliminaValutaUfficio";


        var idValuta = 0;//parseInt($("#idValuta").select2('val'));
        var idUfficio = parseInt($("#idUfficio").select2('val'));

        //if (isNaN(idValuta)) {
        //    $("#divPViewParametri").empty();
        //    return false;
        //}

        var chk = false;
        if ($("#escludiAnnullati").is(":checked")) {
            chk = true;
        }

        $('#dialog-confirm').dialog({
            autoOpen: true,
            width: 400,
            buttons: [
                {
                    text: "OK",
                    click: function () {
                        $(this).dialog("close");
                        $.ajax({
                            type: "POST",
                            url: rotta,
                            data: { escludiAnnullati: chk, idValuta: idValuta, idValutaUfficio: id ,idUfficio: idUfficio},
                            dataType: 'html',
                            beforeSend: function () {
                                //debugger;
                                //VerificaAutenticazione();
                                //$("#DialogNewDoc").dialog("destroy");
                                //$("#divEffettoLoadAutNoDoc").show("slow");

                            },
                            success: function (result) {
                                //debugger;
                                //$("#divEffettoLoadAutNoDoc").hide("slow");
                                $("#divPViewParametri").empty();
                                $("#divPViewParametri").html(result);

                                //RicercaDocumenti();

                            },
                            complete: function () {
                                //$("#divEffettoLoadAutNoDoc").hide("slow");
                                //                $("#Centro").getNiceScroll().resize();
                            },
                            error: function (jqXHR, textStatus, errorThrow) {
                                //debugger;
                                var msg = errorThrow.err;
                                AlertDialog(msg);
                            }

                        });
                    },
                    "class": "ui-button-danger"
                },
                {
                    text: "Annulla",
                    click: function () {
                        $(this).dialog("close");
                    }
                }
            ]
        });

    }

</script>