NewISE/Areas/Statistiche/Controllers/StoriaDipendenteNewController.cs
using NewISE.Models;
using NewISE.Models.DBModel;
using NewISE.Models.dtObj;
using NewISE.Models.DBModel.dtObj;
using NewISE.Models.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using NewISE.EF;
using NewISE.Areas.Statistiche.Models;
using System.Web.UI.WebControls;

namespace NewISE.Areas.Statistiche.Controllers
{
    public class StoriaDipendenteNewController : Controller
    {
        // GET: Statistiche/StoriaDipendenteNew
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult DipendentiGepe(string matricola = "")
        {
            var rMatricola = new List<SelectListItem>();
            var rNominativo = new List<SelectListItem>();
            bool admin = false;
            List<DipendentiModel> ldm = new List<DipendentiModel>();
            DipendentiModel dm = new DipendentiModel();
            AccountModel ac = new AccountModel();
            try
            {

                admin = Utility.Amministratore(out ac);

                using (dtDipendenti dtd = new dtDipendenti())
                {
                    if (!admin)
                    {
                        ldm.Add(dtd.GetDipendenteByMatricola(Convert.ToInt16(ac.utente)));
                    }
                    else if (matricola != string.Empty && admin == false)
                    {
                        ldm.Add(dtd.GetDipendenteByMatricola(Convert.ToInt16(matricola)));
                    }
                    else
                    {
                        ldm = dtd.GetDipendenti().ToList();
                    }

                    if (ldm.Count > 0)
                    {
                        foreach (var item in ldm)
                        {
                            rMatricola.Add(new SelectListItem()
                            {
                                Text = item.matricola.ToString(),
                                Value = item.matricola.ToString()
                            });

                            rNominativo.Add(new SelectListItem()
                            {
                                Text = item.Nominativo + " (" + item.matricola.ToString() + ")",
                                Value = item.matricola.ToString()
                            });

                        }

                        rMatricola.Insert(0, new SelectListItem() { Text = "", Value = "" });

                        rNominativo.Insert(0, new SelectListItem() { Text = "", Value = "" });

                        if (matricola == string.Empty)
                        {
                            rMatricola.First().Selected = true;
                            rNominativo.First().Selected = true;
                        }
                        else
                        {
                            foreach (var item in rMatricola)
                            {
                                if (matricola == item.Value)
                                {
                                    item.Selected = true;
                                }
                            }

                            foreach (var item in rNominativo)
                            {
                                if (matricola == item.Value)
                                {
                                    item.Selected = true;
                                }
                            }
                        }
                    }
                }


                if (matricola != string.Empty)
                {
                    dm = ldm.Where(a => a.matricola == Convert.ToInt16(matricola)).First();

                    using (dtCDCGepe dtcdcg = new dtCDCGepe())
                    {
                        dm.cdcGepe = dtcdcg.GetCDCGepe(dm.idDipendente);
                    }

                    using (dtLivelliDipendente dtpl = new dtLivelliDipendente())
                    {
                        dm.livelloDipendenteValido = dtpl.GetLivelloDipendente(dm.idDipendente, DateTime.Now.Date);
                    }
                }


                //ViewBag.ListDipendentiGepeMatricola = rMatricola.OrderBy(a=>a.Text);
                ViewBag.ListDipendentiGepeNominativo = rNominativo.OrderBy(a => a.Text);
                ViewBag.Amministratore = admin;
                ViewBag.Matricola = dm.matricola;
                ViewBag.Nominativo = dm.Nominativo;
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }

            return PartialView(dm);
        }
        public ActionResult RptStoriaDipendenteNew(decimal Nominativo)
        {
            List<StoriaDipendenteNewModel> rim = new List<StoriaDipendenteNewModel>();
            List<RptStoriaDipendenteNewModel> rpt = new List<RptStoriaDipendenteNewModel>();

            try
            {

                using (ModelDBISE db = new ModelDBISE())
                {
                    using (dtStoriaDipendenteNew dtSD = new dtStoriaDipendenteNew())
                    {
                        rim = dtSD.GetStoriaDipendenteNew(Nominativo, db).ToList().OrderBy(a => a.dataPartenza).ToList();
                    }

                    if (rim?.Any() ?? false)
                    {
                        decimal ordinamento = 0;
                        foreach (var lm in rim)
                        {
                            ordinamento++;

                            RptStoriaDipendenteNewModel rptds = new RptStoriaDipendenteNewModel()
                            {
                                nome = lm.nome,
                                dataAssunzione = lm.dataAssunzione.ToShortDateString(),
                                dataVariazione = lm.dataVariazione,
                                Ufficio = lm.Ufficio,
                                DescLivello =  lm.DescLivello,
                                dataPartenza = lm.dataPartenza.ToShortDateString(),
                                dataRientro = (lm.dataRientro < Utility.DataFineStop()) ? Convert.ToDateTime(lm.dataRientro).ToShortDateString() : " ",
                                valore = lm.valore,
                                percentuale = lm.percentuale,
                                indennita = lm.indennita,
                                ValutaUfficio = lm.ValutaUfficio,
                                IndennitaBase = lm.IndennitaBase,
                                IndennitaPersonale = lm.IndennitaPersonale,
                                IndennitaServizio = lm.IndennitaServizio,
                                MaggiorazioniFamiliari = lm.MaggiorazioniFamiliari,
                                PensioneConiuge = lm.PensioneConiuge,
                                PrimaSistemazione = lm.PrimaSistemazione,
                                ordinamento = ordinamento                               
                            };

                            rpt.Add(rptds);

                        }
                    }

                    string strDataOdierna = DateTime.Now.ToShortDateString();

                    ReportViewer reportViewer = new ReportViewer();

                    reportViewer.ProcessingMode = ProcessingMode.Local;
                    reportViewer.SizeToReportContent = true;
                    reportViewer.Width = Unit.Percentage(100);
                    reportViewer.Height = Unit.Percentage(100);

                    var datasource = new ReportDataSource("DataSetStoriaDipendenteNew");

                    reportViewer.Visible = true;
                    reportViewer.ProcessingMode = ProcessingMode.Local;

                    reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"\Areas\Statistiche\RPT\RptStoriaDipendenteNew.rdlc";

                    ReportParameter[] parameterValues = new ReportParameter[]
                    {
                        new ReportParameter ("paramDataOdierna", strDataOdierna)
                    };
                    reportViewer.LocalReport.SetParameters(parameterValues);

                    reportViewer.LocalReport.DataSources.Clear();
                    reportViewer.LocalReport.DataSources.Add(datasource);
                    reportViewer.LocalReport.DataSources.Add(new ReportDataSource("DataSetStoriaDipendenteNew", rpt));
                    reportViewer.LocalReport.Refresh();

                    ViewBag.ReportViewer = reportViewer;

                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }

            return PartialView("RptStoriaDipendenteNew");
        }

    }
}

NewISE/Areas/Statistiche/Views/StoriaDipendenteNew/DipendentiGepe.cshtml
<div id="dialog "></div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <div class="panel panel-default">
                <div class="panel-heading text-center" style="background-color:lightgrey"><h4><b>Storia del Dipendente</b></h4></div>
                <div class="panel-body" style="font-size:1.2em">
                    <div class="row">
                        <div class="col-xs-4">
                            <strong>Nominativo</strong>
                        </div>
                        <div class="col-xs-4">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4 date">
                            <div class="input-group input-append date">
                                @Html.DropDownList("matricola", ViewBag.ListDipendentiGepeNominativo as IEnumerable<SelectListItem>, new { @id = "Nominativo", @class = "form-control select2 select2-select" })
                            </div>
                            <div id="divNominativo" hidden>
                                <i class="fa fa-asterisk text-danger"></i>
                                <span class="text-danger">Campo obbligatorio</span>
                            </div>
                        </div>

                        <div class="col-xs-4 date">
                            <div class="input-group input-append date">
                                <button class="btn btn-small btn-success" id="opener">
                                    <i aria-hidden="true" class="fa fa-2x fa-print"></i>
                                    Stampa
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


    var windowWidth = $(window).width();
    var windowHeight = $(window).height();


    $("#dialog").dialog({
        autoOpen: false,
        show: {
            //effect: "blind",
            //duration: 1000
        },
        hide: {
            //effect: "explode",
            //duration: 1000
        },
        close: function (event, ui) {
            $('.container').removeClass("NoOverflow");
        },
        height: windowHeight, width: windowWidth


    });

    function Validazione() {
        //debugger;

        var ret = false;
        var c1 = false;

        var nominativo = $("#Nominativo").val();

        if (nominativo != "" && nominativo != undefined) {
            $("#divNominativo").hide();
            c1 = true;
        }
        else {
            $("#divNominativo").show();
            c1 = false;
        }

        if (c1 == false) {
            ret = false;
        }
        else {
            ret = true;
        }

        return ret;
    }


    $("#opener").on("click", function () {
        //debugger;
        if (Validazione()) {

            var rotta = "/Statistiche/StoriaDipendenteNew/RptStoriaDipendenteNew";

            var Nominativo = $("#Nominativo").val();

            $.ajax({
                type: "POST",
                url: rotta,
                data: {
                    Nominativo: Nominativo
                },
                dataType: 'html',
                beforeSend: function () {
                    //debugger;
                    $("#dialog").empty();

                },
                success: function (result) {
                    //debugger;
                    $('.container').addClass("NoOverflow");
                    $("#dialog").dialog("open");
                    $("#dialog").css("background-color", "#ffffff");
                    $("#dialog").html(result);


                },
                complete: function () {
                    //$("#divEffettoLoadAutNoDoc").hide("slow");
                    //                $("#Centro").getNiceScroll().resize();
                },
                error: function (jqXHR, textStatus, errorThrow) {
                    //debugger;
                    var msg = errorThrow.err;
                    AlertDialog(msg);
                }

            });
        }
    });

    $("#Nominativo").select2({
        placeholder: "Seleziona il Nominativo",
        allowClear: true,
        language: "it",
        width: '250',
        allowClear: false

    });



</script>

NewISE/Areas/Statistiche/Views/StoriaDipendenteNew/Index.cshtml
<div class="row">
    <div class="col-xs-12">
        <div>
            @Html.Action("DipendentiGepe", "StoriaDipendenteNew")
        </div>
    </div>

</div>

NewISE/Areas/Statistiche/Views/StoriaDipendenteNew/RptStoriaDipendenteNew.cshtml
@using ReportViewerForMvc;
@using Microsoft.Reporting.WebForms;

<div class="text-center">
    @Html.ReportViewer(
    ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer,
    new { scrolling = "no" })
</div>