NewISE/Areas/Statistiche/Controllers/_old_controllers/RiepiloghiSpeseDiverseController.cs
using Microsoft.Reporting.WebForms;
using NewISE.Areas.Statistiche.Models;
using NewISE.EF;
using NewISE.Models;
using NewISE.Models.DBModel;
using NewISE.Models.DBModel.dtObj;
using NewISE.Models.dtObj.ModelliCalcolo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace NewISE.Areas.Statistiche.Controllers
{
    public class RiepiloghiSpeseDiverseController : Controller
    {
        // GET: Statistiche/RiepiloghiSpeseDiverse
        public ActionResult Index()
        {
            return PartialView();
        }

        public JsonResult PrelevaMesiAnniElab(string search)
        {
            List<Select2Model> ls2 = new List<Select2Model>();
            List<MeseAnnoElaborazioneModel> lmaem = new List<MeseAnnoElaborazioneModel>();

            try
            {
                using (dtElaborazioni dte = new dtElaborazioni())
                {


                    lmaem = dte.PrelevaAnniMesiElaborati().ToList();

                    foreach (var mae in lmaem)
                    {
                        Select2Model s2 = new Select2Model()
                        {
                            id = mae.idMeseAnnoElab.ToString(),
                            text = CalcoloMeseAnnoElaborazione.NomeMese((EnumDescrizioneMesi)mae.mese) + "-" + mae.anno.ToString(),
                        };

                        ls2.Add(s2);
                    }



                }

                if (search != null && search != string.Empty)
                {
                    ls2 = ls2.Where(a => a.text.ToUpper().Contains(search.ToUpper())).ToList();

                }
            }
            catch (Exception ex)
            {

                return Json(new { results = new List<Select2Model>(), err = ex.Message });
            }

            return Json(new { results = ls2, err = "" });
        }

        public ActionResult SelezionaMeseAnno(int mese = 0, int anno = 0)
        {
            var rMeseAnno = new List<SelectListItem>();
            List<MeseAnnoElaborazioneModel> lmaem = new List<MeseAnnoElaborazioneModel>();

            try
            {
                if (anno == 0)
                {
                    anno = DateTime.Now.Year;
                }

                if (mese == 0)
                {
                    mese = DateTime.Now.Month;
                }

                using (dtElaborazioni dte = new dtElaborazioni())
                {
                    lmaem = dte.PrelevaAnniMesiElaborati().ToList();

                    foreach (var item in lmaem)
                    {

                        rMeseAnno.Add(new SelectListItem()
                        {
                            Text = CalcoloMeseAnnoElaborazione.NomeMese((EnumDescrizioneMesi)item.mese) + "-" + item.anno.ToString(),
                            Value = item.idMeseAnnoElab.ToString()
                        });

                    }

                    if (rMeseAnno.Exists(a => a.Text == CalcoloMeseAnnoElaborazione.NomeMese((EnumDescrizioneMesi)mese) + "-" + anno.ToString()))
                    {
                        foreach (var item in rMeseAnno)
                        {
                            if (item.Text == CalcoloMeseAnnoElaborazione.NomeMese((EnumDescrizioneMesi)mese) + "-" + anno.ToString())
                            {
                                item.Selected = true;
                            }
                        }
                    }
                    else
                    {
                        rMeseAnno.First().Selected = true;
                    }

                }

                ViewData["ElencoMesiAnniElaborati"] = rMeseAnno;
                ViewData["ElencoMesiAnniElaborati1"] = rMeseAnno;
            }
            catch (Exception ex)
            {

                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }

            return PartialView();
        }

        //public ActionResult RptRiepiloghiSpeseDiverse(decimal dtIni, decimal dtFin)
        //{
        //    List<RiepiloghiIseMensileModel> rim = new List<RiepiloghiIseMensileModel>();
        //    List<RptRiepiloghiIseMensileModel> rpt = new List<RptRiepiloghiIseMensileModel>();

        //    try
        //    {

        //        using (ModelDBISE db = new ModelDBISE())
        //        {
        //            using (dtRiepiloghiIseMensile dtRiepiloghiIseMensile = new dtRiepiloghiIseMensile())
        //            {
        //                //rim = dtRiepiloghiIseMensile.GetRiepiloghiIseMensile(dtIni, dtFin, db).ToList();
        //            }

        //            if (rim?.Any() ?? false)
        //            {
        //                foreach (var lm in rim)
        //                {
        //                    RptRiepiloghiIseMensileModel rptds = new RptRiepiloghiIseMensileModel()
        //                    {
        //                        IdTeorici = lm.idTeorici,
        //                        DescrizioneVoce = lm.Voci.descrizione,
        //                        Nominativo = lm.Nominativo,
        //                        Movimento = lm.TipoMovimento.DescMovimento,
        //                        Liquidazione = lm.Voci.TipoLiquidazione.descrizione,
        //                        Voce = lm.Voci.codiceVoce,
        //                        //Inserimento = lm.tipoInserimento.ToString(),
        //                        Importo = lm.Importo,
        //                        Inviato = lm.Elaborato,
        //                        meseRiferimento = lm.meseRiferimento

        //                    };

        //                    rpt.Add(rptds);
        //                }
        //            }

        //            var annoMeseElab = db.MESEANNOELABORAZIONE.Find(dtIni);
        //            decimal annoMese = Convert.ToDecimal(annoMeseElab.ANNO.ToString() + annoMeseElab.MESE.ToString().PadLeft(2, Convert.ToChar("0")));

        //            var annoMeseElab1 = db.MESEANNOELABORAZIONE.Find(dtFin);
        //            decimal annoMese1 = Convert.ToDecimal(annoMeseElab1.ANNO.ToString() + annoMeseElab1.MESE.ToString().PadLeft(2, Convert.ToChar("0")));

        //            ReportViewer reportViewer = new ReportViewer();

        //            reportViewer.ProcessingMode = ProcessingMode.Local;
        //            reportViewer.SizeToReportContent = true;
        //            reportViewer.Width = Unit.Percentage(100);
        //            reportViewer.Height = Unit.Percentage(100);

        //            var datasource = new ReportDataSource("DataSetRiepiloghiIseMensile");

        //            reportViewer.Visible = true;
        //            reportViewer.ProcessingMode = ProcessingMode.Local;

        //            reportViewer.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"\Areas\Statistiche\RPT\RptRiepiloghiIseMensile.rdlc";
        //            reportViewer.LocalReport.DataSources.Clear();

        //            reportViewer.LocalReport.DataSources.Add(datasource);
        //            reportViewer.LocalReport.DataSources.Add(new ReportDataSource("DataSetRiepiloghiIseMensile", rpt));
        //            reportViewer.LocalReport.Refresh();

        //            // Nel caso in cui passo il DatePicker
        //            //ReportParameter[] parameterValues = new ReportParameter[]
        //            //   {
        //            //        new ReportParameter ("Dal",Convert.ToString(dtIni)),
        //            //        new ReportParameter ("Al",Convert.ToString(dtFin))
        //            //   };


        //            ReportParameter[] parameterValues = new ReportParameter[]
        //               {
        //                new ReportParameter ("Dal",Convert.ToString(annoMese)),
        //                new ReportParameter ("Al",Convert.ToString(annoMese1))
        //               };

        //            reportViewer.LocalReport.SetParameters(parameterValues);
        //            ViewBag.ReportViewer = reportViewer;

        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
        //    }

        //    return PartialView("RptRiepiloghiIseMensile");
        //}

    }
}

NewISE/Areas/Statistiche/Views/_old_view/RiepiloghiSpeseDiverse/Index.cshtml
<div class="row">
    <div class="col-xs-12">
        <div>
            @Html.Action("SelezionaMeseAnno", "RiepiloghiSpeseDiverse")
        </div>
    </div>

</div>

NewISE/Areas/Statistiche/Views/_old_view/RiepiloghiSpeseDiverse/SelezionaMeseAnno.cshtml
<div id="dialog"></div>


<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <div class="panel panel-default">
                <div class="panel-heading"><b>Riepilogo delle Operazioni Effettuate - Spese Diverse</b></div>
                <div class="panel-body">

                    <div class="col-xs-4 date">
                        <div class="input-group input-append date">
                            @Html.DropDownList("mesiAnniElaborati", ViewData["ElencoMesiAnniElaborati"] as IEnumerable<SelectListItem>, new { @id = "mesiAnniElaborati", @class = "form-control select2 select2-select js-data-example-ajax" })

                        </div>
                    </div>

                    <div class="col-xs-4 date">
                        <div class="input-group input-append date">
                            @Html.DropDownList("mesiAnniElaborati", ViewData["ElencoMesiAnniElaborati"] as IEnumerable<SelectListItem>, new { @id = "mesiAnniElaborati1", @class = "form-control select2 select2-select js-data-example-ajax" })

                        </div>
                    </div>

                    <div class="col-xs-4 date">
                        <div class="input-group input-append date">
                            <button class="btn btn-small btn-default" id="opener">
                                <i aria-hidden="true" class="fa fa-2x fa-print"></i>

                                Stampa
                            </button>
                        </div>
                    </div>

                    @*<div class="col-xs-2 date">

                            <div class="input-group input-append date">
                                <input type="text" class="form-control" id="data1" />
                                <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                        </div>

                        <div class="col-xs-2 date">

                            <div class="input-group input-append date">
                                <input type="text" class="form-control" id="data2" />
                                <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                            </div>
                        </div>*@


                    @*<div class="col-md-3">
                            <a href="#" onclick="callpartialRptOpIndSedeEstera()">Test </a>

                        </div>*@

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">


    $("#mesiAnniElaborati").select2({
        placeholder: "Seleziona il mese-anno",
        allowClear: false,
        language: "it",
        width: '150',
        ajax: {
            delay: 250,
            url: "/RiepiloghiSpeseDiverse/PrelevaMesiAnniElab",
            data: function (dati) {
                //debugger;
                var query = {
                    search: dati.term,
                    type: 'public'
                }

                // Query parameters will be ?search=[term]&type=public
                return query;
            },
            dataType: 'json',
            type: "post",
            processResults: function (data) {
                //debugger;
                return {
                    results: data.results
                }
            }
        }
    });

    $("#mesiAnniElaborati").change(function () {
        //debugger;

        if (this.value != "") {
            var valore = this.value;

        }

    });

    $("#mesiAnniElaborati1").select2({
        placeholder: "Seleziona il mese-anno",
        allowClear: false,
        language: "it",
        width: '150',
        ajax: {
            delay: 250,
            url: "/RiepiloghiSpeseDiverse/PrelevaMesiAnniElab",
            data: function (dati) {
                //debugger;
                var query = {
                    search: dati.term,
                    type: 'public'
                }

                // Query parameters will be ?search=[term]&type=public
                return query;
            },
            dataType: 'json',
            type: "post",
            processResults: function (data) {
                //debugger;
                return {
                    results: data.results
                }
            }
        }
    });

    $("#mesiAnniElaborati1").change(function () {
        //debugger;

        if (this.value != "") {
            var valore = this.value;

        }

    });

    function ValorizzazioneIniziale() {
        //debugger;
        var valore = $("#mesiAnniElaborati").val();

    }



    $(".form-control:input").datepicker();

    var windowWidth = $(window).width();
    var windowHeight = $(window).height();


    $("#dialog").dialog({
        autoOpen: false,
        show: {
            //effect: "blind",
            //duration: 1000
        },
        hide: {
            //effect: "explode",
            //duration: 1000
        },
        close: function (event, ui) {
            $('.container').removeClass("NoOverflow");
        },
        height: windowHeight, width: windowWidth


    });

    $("#opener").on("click", function () {
        //debugger;

        $('.container').addClass("NoOverflow");

        $("#dialog").dialog("open");
        $("#dialog").css("background-color", "#ffffff");


        var rotta = "/Statistiche/RiepiloghiSpeseDiverse/RptRiepiloghiSpeseDiverse";

        //var data1 = $("#data1").datepicker().val()
        //var data2 = $("#data2").datepicker().val()

        var data1 = $("#mesiAnniElaborati").val();
        var data2 = $("#mesiAnniElaborati1").val();

        $.ajax({
            type: "POST",
            url: rotta,
            data: {
                dtIni: data1,
                dtFin: data2
            },
            dataType: 'html',
            beforeSend: function () {
                //debugger;
                $("#dialog").empty();

            },
            success: function (result) {
                //debugger;
                $("#dialog").html(result);


            },
            complete: function () {
                //$("#divEffettoLoadAutNoDoc").hide("slow");
                //                $("#Centro").getNiceScroll().resize();
            },
            error: function (jqXHR, textStatus, errorThrow) {
                //debugger;
                var msg = errorThrow.err;
                AlertDialog(msg);
            }

        });

    });

    $("#mesiAnniElaborati").select2({
        placeholder: "Seleziona la Data Dal",
        allowClear: true,
        language: "it",
        width: '170',
        allowClear: false

    });


    $("#mesiAnniElaborati1").select2({
        placeholder: "Seleziona la Data Al",
        allowClear: true,
        language: "it",
        width: '170',
        allowClear: false

    });


</script>