NewISE/Controllers/VariazioneTrasportoEffettiController.cs
using System.Web.Routing;
using NewISE.EF;
using NewISE.Models.Tools;
using Newtonsoft.Json;
using System.IO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewISE.Models;
using NewISE.Models.DBModel;
using NewISE.Models.DBModel.dtObj;
using NewISE.Models.ViewModel;
using NewISE.Interfacce;
using NewISE.Models.dtObj.ModelliCalcolo;
using NewISE.Models.Enumeratori;

namespace NewISE.Controllers
{
    public class VariazioneTrasportoEffettiController : Controller
    {
        [HttpPost]
        public ActionResult VariazioneTE(decimal idTrasferimento)
        {
            try
            {
                using (dtVariazioneTrasportoEffetti dtvte = new dtVariazioneTrasportoEffetti())
                {
                    var idTEPartenza = dtvte.GetTEPartenzaByIdTrasferimento(idTrasferimento).idTEPartenza;
                    if (idTEPartenza > 0)
                    {
                        ViewData.Add("idTrasferimento", idTrasferimento);
                        ViewData.Add("idTEPartenza", idTEPartenza);
                    }

                    return PartialView();

                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult VariazioneTERientro(decimal idTrasferimento)
        {
            try
            {
                using (dtVariazioneTrasportoEffetti dtvte = new dtVariazioneTrasportoEffetti())
                {
                    var idTERientro = dtvte.GetTERientroByIdTrasferimento(idTrasferimento).idTERientro;
                    if (idTERientro > 0)
                    {
                        ViewData.Add("idTrasferimento", idTrasferimento);
                        ViewData.Add("idTERientro", idTERientro);
                    }

                    return PartialView();

                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }
        }



        [HttpPost]
        public ActionResult VariazioneTEP(decimal idTEPartenza)
        {
            try
            {
                using (ModelDBISE db = new ModelDBISE())
                {
                    using (dtVariazioneTrasportoEffetti dtvte = new dtVariazioneTrasportoEffetti())
                    {
                        using (dtTrasferimento dtt = new dtTrasferimento())
                        {
                            bool richiestaTE = false;
                            bool attivazioneTE = false;
                            bool DocAttestazione = false;
                            bool trasfAnnullato = false;
                            bool siAnticipo = false;
                            bool rinunciaTE = false;
                            decimal anticipoPercepito = 0;

                            VariazioneTEPartenzaModel vtepm = new VariazioneTEPartenzaModel();

                            var atep = dtvte.GetUltimaAttivazioneTEPartenza(idTEPartenza, db);

                            dtvte.SituazioneTEPartenza(idTEPartenza,
                                                        out richiestaTE,
                                                        out attivazioneTE,
                                                        out DocAttestazione,
                                                        out siAnticipo,
                                                        out anticipoPercepito,
                                                        out rinunciaTE,
                                                        out trasfAnnullato);

                            var tm = dtt.GetTrasferimentoByIdTEPartenza(idTEPartenza);

                            var t = dtt.GetTrasferimento(tm.idTrasferimento, db);

                            //legge indennita PS su TEORICI
                            var lteorici = t.TEORICI.Where(x =>
                                           x.VOCI.IDTIPOLIQUIDAZIONE == (decimal)EnumTipoLiquidazione.Paghe &&
                                           //x.ELABORATO &&
                                           x.DIRETTO == false &&
                                           x.IDVOCI == (decimal)EnumVociCedolino.Trasp_Mass_Partenza_Rientro_162_131 &&
                                           x.INSERIMENTOMANUALE == false &&
                                           x.ANNULLATO == false &&
                                           x.ELABTRASPEFFETTI.CONGUAGLIO == false &&
                                           x.ELABTRASPEFFETTI.SALDO &&
                                           x.ELABTRASPEFFETTI.IDTEPARTENZA > 0 &&
                                           x.ANNORIFERIMENTO == t.DATAPARTENZA.Year &&
                                           x.MESERIFERIMENTO == t.DATAPARTENZA.Month)
                                       .ToList();

                            decimal indennitaPS = 0;
                            decimal percentualeFKMPartenza = 0;
                            decimal contributoLordo = 0;

                            if (lteorici?.Any() ?? false)
                            {
                                var teorici = lteorici.First();
                                indennitaPS = teorici.IMPORTOLORDO;
                                percentualeFKMPartenza = teorici.ELABTRASPEFFETTI.PERCENTUALEFK;
                                contributoLordo = indennitaPS * percentualeFKMPartenza / 100;
                            }
                            else
                            {
                                CalcoliIndennita ci = new CalcoliIndennita(tm.idTrasferimento, tm.dataPartenza);

                                indennitaPS = ci.IndennitaSistemazioneLorda;
                                percentualeFKMPartenza = ci.PercentualeFKMPartenza;
                                //contributoLordo = ci.TotaleContributoOmnicomprensivoPartenza;
                                contributoLordo = indennitaPS * percentualeFKMPartenza / 100;
                            }

                            vtepm.indennitaPrimaSistemazione = Math.Round(indennitaPS, 2);
                            vtepm.percKM = percentualeFKMPartenza;
                            vtepm.contributoLordo = Math.Round(contributoLordo, 2);
                            vtepm.anticipoPercepito = anticipoPercepito;
                            vtepm.saldo = Math.Round(vtepm.contributoLordo - vtepm.anticipoPercepito, 2);

                            //se ho rinunciato imposto la form con dati a zero e blocco l'inserimento di documenti
                            if (rinunciaTE)
                            {
                                siAnticipo = false;
                                vtepm.anticipoPercepito = 0;
                                vtepm.saldo = 0;
                            }

                            vtepm.siAnticipo = siAnticipo;

                            ViewData.Add("richiestaTE", richiestaTE);
                            ViewData.Add("rinunciaTE", rinunciaTE);
                            ViewData.Add("attivazioneTE", attivazioneTE);
                            ViewData.Add("DocAttestazione", DocAttestazione);
                            ViewData.Add("idTEPartenza", idTEPartenza);

                            return PartialView(vtepm);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                return PartialView("ErrorPartial", new MsgErr() { msg = ex.Message });
            }

        }

        [HttpPost]
        public ActionResult VariazioneTER(decimal idTERientro)
        {
            try
            {
                using (ModelDBISE db = new ModelDBISE())
                {
                    using (dtVariazioneTrasportoEffetti dtvte = new dtVariazioneTrasportoEffetti())
                    {
                        using (dtTrasferimento dtt = new dtTrasferimento())
                        {
                            bool richiestaTER = false;
                            bool attivazioneTER = false;
                            bool DocAttestazione = false;
                            bool trasfAnnullato = false;
                            bool siAnticipo = false;
                            bool rinunciaTER = false;
                            decimal anticipoPercepito = 0;

                            VariazioneTERientroModel vterm = new VariazioneTERientroModel();

                            var ater = dtvte.GetUltimaAttivazioneTERientro(idTERientro, db);

                            dtvte.SituazioneTERientro(idTERientro,
                                                        out richiestaTER,
                                                        out attivazioneTER,
                                                        out DocAttestazione,
                                                        out siAnticipo,
                                                        out anticipoPercepito,
                                                        out rinunciaTER,
                                                        out trasfAnnullato);

                            var tm = dtt.GetTrasferimentoByIdTERientro(idTERientro);

                            var t = dtt.GetTrasferimento(tm.idTrasferimento, db);

                            //legge indennita PS su TEORICI
                            var lteorici = t.TEORICI.Where(x =>
                                           x.VOCI.IDTIPOLIQUIDAZIONE == (decimal)EnumTipoLiquidazione.Paghe &&
                                           //x.ELABORATO &&
                                           x.DIRETTO == false &&
                                           x.IDVOCI == (decimal)EnumVociCedolino.Trasp_Mass_Partenza_Rientro_162_131 &&

NewISE/Views/VariazioneTrasportoEffetti/ElencoDocumentiVariazioneTEP.cshtml
@using NewISE.Models.DBModel
@using NewISE.Models.Enumeratori
@{
    string DescrizioneTE = Convert.ToString(ViewData["DescrizioneTE"]);
    decimal idTipoDocumento = Convert.ToDecimal(ViewData["idTipoDocumento"]);
    decimal idTEPartenza = Convert.ToDecimal(ViewData["idTEPartenza"]);
    bool richiestaVariazioneTEPartenza = Convert.ToBoolean(ViewData["richiestaVariazioneTEPartenza"]);
    decimal idStatoTrasferimento = Convert.ToDecimal(ViewData["idStatoTrasferimento"]);
    bool attivazioneVariazioneTEPartenza = Convert.ToBoolean(ViewData["attivazioneVariazioneTEPartenza"]);
//    decimal NumAttivazioniTEPartenza = Convert.ToDecimal(ViewData["NumAttivazioniTEPartenza"]);
}

@Html.Hidden("hiNuovoDocumento")

@Html.Hidden("hIdDocumentoTE")




<p style="margin-top: 10px">
    <div class="row">
        <div class="col-xs-12" style="margin-left:15px;">
            <h4>Elenco documentazione @DescrizioneTE</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-3">
            <div style="margin-top: 10px; margin-bottom: 10px; margin-left:15px">
                @if (idTipoDocumento == (decimal)EnumTipoDoc.Attestazione_Trasloco)
                {
                    <a class="btn btn-default btn-sm" href="~/FormulariMaster/FormularioTE/modulo 3.pdf" target="_blank">
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Download Formulario
                    </a>
                }
            </div>
        </div>
        <div class="col-xs-3">
            <div style="margin-top: 10px; margin-bottom: 10px;">
                @if (
                    richiestaVariazioneTEPartenza == false
                    &&
                    attivazioneVariazioneTEPartenza == false
                    &&
                    idTipoDocumento == (decimal)EnumTipoDoc.Attestazione_Trasloco
                    &&
                    idStatoTrasferimento != (decimal)EnumStatoTraferimento.Annullato
                )
                {
                    <button class="btn btn-default btn-sm" onclick="NuovoDocumentoVariazioneTE();">
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Aggiungi Documento
                    </button>
                }
                else
                {
                    <button class="btn btn-default btn-sm" disabled>
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Aggiungi Documento
                    </button>
                }
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-xs-12">
            <div id="divTabElencoDocumentiVariazioneTE" style="margin-left:15px;margin-right:15px;">
                @Html.Action("TabDocumentiVariazioneTEPInseriti", "VariazioneTrasportoEffetti", new { idTEPartenza = idTEPartenza, idTipoDocumento = idTipoDocumento })
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalNuovoDocumentoVariazioneTE" tabindex="-1" role="dialog" aria-labelledby="ModalNuovoDocumentoVariazioneTELabel" aria-hidden="true">
        <div class="modal-dialog  modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title alert alert-info text-info" id="NuovoDocumentoVariazioneTELabel">Nuovo documento @DescrizioneTE</h3>
                </div>
                <div class="modal-body alert alert-info text-info" style="font-size: 1em;">
                    <div id="divViewNuovoDocumentoVariazioneTE">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalEliminaDocumentoVariazioneTE" tabindex="-1" role="dialog" aria-labelledby="ModalEliminaDocumentoVariazioneTELabel" aria-hidden="true" >
        <div class="modal-dialog modal-lg" role="document" >
            <div class="modal-content" >
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title alert alert-info text-info" id="EliminaDocumentoVariazioneTELabel">Elimina @DescrizioneTE</h3>
                </div>

                <div class="modal-body alert alert-info text-info" style="font-size: 1em">
                    <input type="hidden" id="hIdDocTE">  <p><label>Eliminare il documento selezionato ?</label></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="ConfermaEliminaDocumentoVariazioneTE(@idTipoDocumento);">Ok</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                </div>
            </div>
        </div>
    </div>

<p style="padding-left: 15px;">
    @Ajax.ActionLink("Torna indietro", "VariazioneTEP", "VariazioneTrasportoEffetti", new { idTEPartenza = idTEPartenza }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divVariazioneTEP", OnFailure = "ErroreElaborazioneAjax", InsertionMode = InsertionMode.Replace })
</p>

<script type="text/javascript">
    $('#hiNuovoDocumento').val(@idTipoDocumento);

    GestionePulsantiNotificaAttivaAnnullaVariazioneTEP();


    function NuovoDocumentoVariazioneTE() {
        //debugger;
        var rotta = "/VariazioneTrasportoEffetti/NuovoDocumentoVariazioneTEP";
        var idTEPartenza= @idTEPartenza;
        var idTipoDocumento = parseInt($("#hiNuovoDocumento").val());

        $.ajax({
            url: rotta,
            type: "POST", //Le info testuali saranno passate in POST
            data: { idTipoDocumento:idTipoDocumento , idTEPartenza: idTEPartenza},
            dataType: 'html',
            async: false,
            beforeSend: function () {
                //debugger;
                VerificaAutenticazione();
                //$('#inviaDocModal').modal('show');
                Blocca();
                $('#ModalNuovoDocumentoVariazioneTE').modal('show');
            },
            success: function (result) {
                //debugger;
                $("#divViewNuovoDocumentoVariazioneTE").empty();
                $("#divViewNuovoDocumentoVariazioneTE").html(result);
            },
            error: function (error) {
                //debugger;
                Sblocca();
                var msg = error.responseText;
                ErroreElaborazioneAjax(msg);
            }
        });
    }

    function TabElencoDocumentiVariazioneTEP() {
        //debugger;
        var rotta = "/VariazioneTrasportoEffetti/TabDocumentiVariazioneTEPInseriti";
        var idTEPartenza = @idTEPartenza;
        var idTipoDocumento = parseInt($("#hiNuovoDocumento").val());

        $.ajax({
            url: rotta,
            type: "POST", //Le info testuali saranno passate in POST
            data: {
                idTEPartenza: idTEPartenza,
                idTipoDocumento:idTipoDocumento
            },
            dataType: 'html',
            async: false,
            beforeSend: function () {
                //debugger;
                VerificaAutenticazione();
                //$('#inviaDocModal').modal('show');
                Blocca();
            },
            success: function (result) {
                //debugger;
                $("#divTabElencoDocumentiVariazioneTE").empty();
                $("#divTabElencoDocumentiVariazioneTE").html(result);
            },
            error: function (error) {
                //debugger;
                Sblocca();
                var msg = error.responseText;
                ErroreElaborazioneAjax(msg);
            }
        });
    }


    $("#ModalNuovoDocumentoVariazioneTE").on("hidden.bs.modal", function () {
        //debugger;
        TabElencoDocumentiVariazioneTEP();
        ElencoDocumentiVariazioneTEP(@idTipoDocumento);
    });

    function EliminaDocumentoVariazioneTE(idDoc) {
        $("#hIdDocumentoTE").val(idDoc);
        $("#ModalEliminaDocumentoVariazioneTE").modal("show");
    }


    $("#ModalEliminaDocumentoVariazioneTE").on("hidden.bs.modal", function () {
        //debugger;
        TabElencoDocumentiVariazioneTEP();
    });

</script>

NewISE/Views/VariazioneTrasportoEffetti/ElencoDocumentiVariazioneTER.cshtml
@using NewISE.Models.DBModel
@using NewISE.Models.Enumeratori
@{
    string DescrizioneTE = Convert.ToString(ViewData["DescrizioneTE"]);
    decimal idTipoDocumento = Convert.ToDecimal(ViewData["idTipoDocumento"]);
    decimal idTERientro = Convert.ToDecimal(ViewData["idTERientro"]);
    bool richiestaVariazioneTER = Convert.ToBoolean(ViewData["richiestaVariazioneTER"]);
    decimal idStatoTrasferimento = Convert.ToDecimal(ViewData["idStatoTrasferimento"]);
    bool attivazioneVariazioneTER = Convert.ToBoolean(ViewData["attivazioneVariazioneTER"]);
}

@Html.Hidden("hiNuovoDocumento")

@Html.Hidden("hIdDocumentoTER")




<p style="margin-top: 10px">
    <div class="row">
        <div class="col-xs-12" style="margin-left:15px;">
            <h4>Elenco documentazione @DescrizioneTE</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-3">
            <div style="margin-top: 10px; margin-bottom: 10px; margin-left:15px">
                @if (idTipoDocumento == (decimal)EnumTipoDoc.Attestazione_Trasloco_Rientro)
                {
                    <a class="btn btn-default btn-sm" href="~/FormulariMaster/FormularioTE/modulo 4.pdf" target="_blank">
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Download Formulario
                    </a>
                }
            </div>
        </div>
        <div class="col-xs-3">
            <div style="margin-top: 10px; margin-bottom: 10px;">
                @if (
                richiestaVariazioneTER == false
                &&
                attivazioneVariazioneTER == false
                &&
                idTipoDocumento == (decimal)EnumTipoDoc.Attestazione_Trasloco_Rientro
                &&
                idStatoTrasferimento != (decimal)EnumStatoTraferimento.Annullato
            )
                {
                    <button class="btn btn-default btn-sm" onclick="NuovoDocumentoVariazioneTER();">
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Aggiungi Documento
                    </button>
                }
                else
                {
                    <button class="btn btn-default btn-sm" disabled>
                        <i aria-hidden="true" class="fa fa-2x fa-file-pdf-o"></i>
                        Aggiungi Documento
                    </button>
                }
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-xs-12">
            <div id="divTabElencoDocumentiVariazioneTER" style="margin-left:15px;margin-right:15px;">
                @Html.Action("TabDocumentiVariazioneTERInseriti", "VariazioneTrasportoEffetti", new { idTERientro = idTERientro, idTipoDocumento = idTipoDocumento })
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalNuovoDocumentoVariazioneTER" tabindex="-1" role="dialog" aria-labelledby="ModalNuovoDocumentoVariazioneTERLabel" aria-hidden="true">
        <div class="modal-dialog  modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title alert alert-info text-info" id="NuovoDocumentoVariazioneTERLabel">Nuovo documento @DescrizioneTE</h3>
                </div>
                <div class="modal-body alert alert-info text-info" style="font-size: 1em;">
                    <div id="divViewNuovoDocumentoVariazioneTER">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Chiudi</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="ModalEliminaDocumentoVariazioneTER" tabindex="-1" role="dialog" aria-labelledby="ModalEliminaDocumentoVariazioneTERLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title alert alert-info text-info" id="EliminaDocumentoVariazioneTERLabel">Elimina @DescrizioneTE</h3>
                </div>

                <div class="modal-body alert alert-info text-info" style="font-size: 1em">
                    <input type="hidden" id="hIdDocTER">
                    <p><label>Eliminare il documento selezionato ?</label></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="ConfermaEliminaDocumentoVariazioneTER(@idTipoDocumento);">Ok</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                </div>
            </div>
        </div>
    </div>
</p>

<p style="padding-left: 15px;">
    @Ajax.ActionLink("Torna indietro", "VariazioneTER", "VariazioneTrasportoEffetti", new { idTERientro = idTERientro }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divVariazioneTER", OnFailure = "ErroreElaborazioneAjax", InsertionMode = InsertionMode.Replace })
</p>

<script type="text/javascript">
    $('#hiNuovoDocumento').val(@idTipoDocumento);

    GestionePulsantiNotificaAttivaAnnullaVariazioneTER();


    function NuovoDocumentoVariazioneTER() {
        //debugger;
        var rotta = "/VariazioneTrasportoEffetti/NuovoDocumentoVariazioneTER";
        var idTERientro= parseInt('@idTERientro');
        var idTipoDocumento = parseInt($("#hiNuovoDocumento").val());

        $.ajax({
            url: rotta,
            type: "POST", //Le info testuali saranno passate in POST
            data: { idTipoDocumento:idTipoDocumento , idTERientro: idTERientro},
            dataType: 'html',
            async: false,
            beforeSend: function () {
                //debugger;
                VerificaAutenticazione();
                //$('#inviaDocModal').modal('show');
                Blocca();
                $('#ModalNuovoDocumentoVariazioneTER').modal('show');
            },
            success: function (result) {
                //debugger;
                $("#divViewNuovoDocumentoVariazioneTER").empty();
                $("#divViewNuovoDocumentoVariazioneTER").html(result);
            },
            error: function (error) {
                //debugger;
                Sblocca();
                var msg = error.responseText;
                ErroreElaborazioneAjax(msg);
            }
        });
    }

    function TabElencoDocumentiVariazioneTER() {
        //debugger;
        var rotta = "/VariazioneTrasportoEffetti/TabDocumentiVariazioneTERInseriti";
        var idTERientro = @idTERientro;
        var idTipoDocumento = parseInt($("#hiNuovoDocumento").val());

        $.ajax({
            url: rotta,
            type: "POST", //Le info testuali saranno passate in POST
            data: {
                idTERientro: idTERientro,
                idTipoDocumento:idTipoDocumento
            },
            dataType: 'html',
            async: false,
            beforeSend: function () {
                //debugger;
                VerificaAutenticazione();
                //$('#inviaDocModal').modal('show');
                Blocca();
            },
            success: function (result) {
                //debugger;
                $("#divTabElencoDocumentiVariazioneTER").empty();
                $("#divTabElencoDocumentiVariazioneTER").html(result);
            },
            error: function (error) {
                //debugger;
                Sblocca();
                var msg = error.responseText;
                ErroreElaborazioneAjax(msg);
            }
        });
    }


    $("#ModalNuovoDocumentoVariazioneTER").on("hidden.bs.modal", function () {
        //debugger;
        TabElencoDocumentiVariazioneTER();
        ElencoDocumentiVariazioneTER(@idTipoDocumento);
    });

    function EliminaDocumentoVariazioneTER(idDoc) {
        $("#hIdDocumentoTER").val(idDoc);
        $("#ModalEliminaDocumentoVariazioneTER").modal("show");
    }


    $("#ModalEliminaDocumentoVariazioneTER").on("hidden.bs.modal", function () {
        //debugger;
        TabElencoDocumentiVariazioneTER();
    });

</script>

NewISE/Views/VariazioneTrasportoEffetti/MessaggioAnnullaVariazioneTEP.cshtml
@model NewISE.Interfacce.ModelloMsgMail

<link href="~/Scripts/cleditor/jquery.cleditor.css" rel="stylesheet" />
<script src="~/Scripts/cleditor/jquery.cleditor.min.js"></script>
@{
    string msgAnnulla = Convert.ToString(Model.corpoMsg);
}

<div class="form-group">
    <div ass="col-md-10">
        @Html.TextAreaFor(model => model.corpoMsg, new { @id = "FullDescriptionVariazioneTEP" })
    </div>
</div>

<script type="text/javascript">
    $("#FullDescriptionVariazioneTEP").cleditor();

    $('#FullDescriptionVariazioneTEP').each(function () {
        this.contentEditable = true;
    });
</script>

NewISE/Views/VariazioneTrasportoEffetti/MessaggioAnnullaVariazioneTER.cshtml
@model NewISE.Interfacce.ModelloMsgMail

<link href="~/Scripts/cleditor/jquery.cleditor.css" rel="stylesheet" />
<script src="~/Scripts/cleditor/jquery.cleditor.min.js"></script>
@{
    string msgAnnulla = Convert.ToString(Model.corpoMsg);
}

<div class="form-group">
    <div ass="col-md-10">
        @Html.TextAreaFor(model => model.corpoMsg, new { @id = "FullDescriptionVariazioneTER" })
    </div>
</div>

<script type="text/javascript">
    $("#FullDescriptionVariazioneTER").cleditor();

    $('#FullDescriptionVariazioneTER').each(function () {
        this.contentEditable = true;
    });
</script>